--------------------------------------------------------
--  File created - Streda-marec-11-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ISSUE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SNECH_DB"."ISSUE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MESSAGES_MESSAGE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SNECH_DB"."MESSAGES_MESSAGE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_LOGIN_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SNECH_DB"."USER_LOGIN_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_ROLES_ROLE_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SNECH_DB"."USER_ROLES_ROLE_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_USER_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SNECH_DB"."USERS_USER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."ATTACHMENTS" 
   (	"ATTACHMENT_ID" NUMBER(*,0), 
	"ISSUE_ID" NUMBER(*,0), 
	"MESSAGE_ID" NUMBER(*,0), 
	"FILE_URL" VARCHAR2(255 BYTE), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"FILE_SIZE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ISSUE_COMMENTS
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."ISSUE_COMMENTS" 
   (	"ISSUE_COMMENT_ID" NUMBER, 
	"ISSUE_ID" NUMBER(*,0), 
	"SUBJECT" VARCHAR2(255 BYTE), 
	"TEXT" CLOB, 
	"CREATED_ON" TIMESTAMP (6), 
	"AUTHOR_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ISSUE_LOGS
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."ISSUE_LOGS" 
   (	"ISSUE_LOG_ID" NUMBER(*,0), 
	"ISSUE_ID" NUMBER(*,0), 
	"ISSUE_LOG_TYPE_ID" NUMBER(*,0), 
	"AUTHOR_ID" NUMBER(*,0), 
	"DESCRIPTION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ISSUE_LOG_TYPES
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."ISSUE_LOG_TYPES" 
   (	"LOG_TYPE_ID" NUMBER(*,0), 
	"LOG_TYPE_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ISSUE_PRIORITIES
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."ISSUE_PRIORITIES" 
   (	"CODE" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(140 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ISSUES
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."ISSUES" 
   (	"ISSUE_ID" NUMBER(*,0), 
	"USER_LOGIN" VARCHAR2(20 BYTE), 
	"SUBJECT" VARCHAR2(1000 BYTE), 
	"CODE_PRIORITY" VARCHAR2(10 BYTE), 
	"CODE_STATUS" VARCHAR2(10 BYTE), 
	"ESTIMATED_TIME" TIMESTAMP (6), 
	"CREATED_ON" TIMESTAMP (6), 
	"LAST_UPDATE" TIMESTAMP (6), 
	"MESSAGE" VARCHAR2(1000 BYTE), 
	"ADMIN_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ISSUE_STATUS
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."ISSUE_STATUS" 
   (	"CODE" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(140 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MESSAGES
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."MESSAGES" 
   (	"MESSAGE_ID" NUMBER(*,0), 
	"FROM_USER_ID" NUMBER(*,0), 
	"TO_USER_ID" NUMBER(*,0), 
	"SUBJECT" VARCHAR2(255 BYTE), 
	"TEXT" VARCHAR2(255 BYTE), 
	"READ" CHAR(1 BYTE), 
	"SENT_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICES
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."NOTICES" 
   (	"NOTICE_ID" NUMBER(*,0), 
	"SUBJECT" VARCHAR2(255 BYTE), 
	"TEXT" CLOB, 
	"CREATED_ON" TIMESTAMP (6), 
	"VISIBLE" CHAR(1 BYTE), 
	"AUTHOR_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("TEXT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table USER_LOGINS
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."USER_LOGINS" 
   (	"LOGIN_ID" NUMBER(*,0), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"USER_ID" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"USER_ROLES_ROLE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_ROLES
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."USER_ROLES" 
   (	"ROLE_ID" NUMBER(*,0), 
	"ROLE_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SNECH_DB"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(255 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"OCCUPATION" VARCHAR2(255 BYTE), 
	"CREATED_ON" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SNECH_DB.ATTACHMENTS
SET DEFINE OFF;
REM INSERTING into SNECH_DB.ISSUE_COMMENTS
SET DEFINE OFF;
REM INSERTING into SNECH_DB.ISSUE_LOGS
SET DEFINE OFF;
REM INSERTING into SNECH_DB.ISSUE_LOG_TYPES
SET DEFINE OFF;
REM INSERTING into SNECH_DB.ISSUE_PRIORITIES
SET DEFINE OFF;
Insert into SNECH_DB.ISSUE_PRIORITIES (CODE,DESCRIPTION) values ('A',null);
Insert into SNECH_DB.ISSUE_PRIORITIES (CODE,DESCRIPTION) values ('B',null);
Insert into SNECH_DB.ISSUE_PRIORITIES (CODE,DESCRIPTION) values ('C',null);
Insert into SNECH_DB.ISSUE_PRIORITIES (CODE,DESCRIPTION) values ('D',null);
Insert into SNECH_DB.ISSUE_PRIORITIES (CODE,DESCRIPTION) values ('E',null);
REM INSERTING into SNECH_DB.ISSUES
SET DEFINE OFF;
Insert into SNECH_DB.ISSUES (ISSUE_ID,USER_LOGIN,SUBJECT,CODE_PRIORITY,CODE_STATUS,ESTIMATED_TIME,CREATED_ON,LAST_UPDATE,MESSAGE,ADMIN_LOGIN) values ('8','robert_u','NullPointerException SR1501','A','NOVA',to_timestamp('10.09.02 14:10:10,123000000','DD.MM.RR HH24:MI:SSXFF'),to_timestamp('10.09.02 14:10:10,123000000','DD.MM.RR HH24:MI:SSXFF'),to_timestamp('10.09.02 14:10:10,123000000','DD.MM.RR HH24:MI:SSXFF'),'Tak toto je sprava','1');
Insert into SNECH_DB.ISSUES (ISSUE_ID,USER_LOGIN,SUBJECT,CODE_PRIORITY,CODE_STATUS,ESTIMATED_TIME,CREATED_ON,LAST_UPDATE,MESSAGE,ADMIN_LOGIN) values ('9','robert_u','SqlException SR1501','A','NOVA',to_timestamp('10.09.02 14:10:10,123000000','DD.MM.RR HH24:MI:SSXFF'),to_timestamp('10.09.02 14:10:10,123000000','DD.MM.RR HH24:MI:SSXFF'),to_timestamp('10.09.02 14:10:10,123000000','DD.MM.RR HH24:MI:SSXFF'),'Tak toto je sprava','1');
REM INSERTING into SNECH_DB.ISSUE_STATUS
SET DEFINE OFF;
Insert into SNECH_DB.ISSUE_STATUS (CODE,DESCRIPTION) values ('NOVA',null);
Insert into SNECH_DB.ISSUE_STATUS (CODE,DESCRIPTION) values ('PREBIEHA',null);
Insert into SNECH_DB.ISSUE_STATUS (CODE,DESCRIPTION) values ('VYRIESENE',null);
Insert into SNECH_DB.ISSUE_STATUS (CODE,DESCRIPTION) values ('ZAMIETNUTE',null);
Insert into SNECH_DB.ISSUE_STATUS (CODE,DESCRIPTION) values ('INY',null);
REM INSERTING into SNECH_DB.MESSAGES
SET DEFINE OFF;
REM INSERTING into SNECH_DB.NOTICES
SET DEFINE OFF;
REM INSERTING into SNECH_DB.USER_LOGINS
SET DEFINE OFF;
Insert into SNECH_DB.USER_LOGINS (LOGIN_ID,LOGIN,USER_ID,PASSWORD,USER_ROLES_ROLE_ID) values ('1','robert_u','1','123','1');
Insert into SNECH_DB.USER_LOGINS (LOGIN_ID,LOGIN,USER_ID,PASSWORD,USER_ROLES_ROLE_ID) values ('2','robert_d','1','123','2');
Insert into SNECH_DB.USER_LOGINS (LOGIN_ID,LOGIN,USER_ID,PASSWORD,USER_ROLES_ROLE_ID) values ('3','robert_a','1','123','3');
REM INSERTING into SNECH_DB.USER_ROLES
SET DEFINE OFF;
Insert into SNECH_DB.USER_ROLES (ROLE_ID,ROLE_NAME) values ('1','user');
Insert into SNECH_DB.USER_ROLES (ROLE_ID,ROLE_NAME) values ('2','developer');
Insert into SNECH_DB.USER_ROLES (ROLE_ID,ROLE_NAME) values ('3','admin');
REM INSERTING into SNECH_DB.USERS
SET DEFINE OFF;
Insert into SNECH_DB.USERS (USER_ID,FIRST_NAME,LAST_NAME,EMAIL,OCCUPATION,CREATED_ON) values ('1','Robert','Langdon','radovan.racak@gmail.com','Developer',to_timestamp('31.12.06 23:34:59,000000000','DD.MM.RR HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index ATTACHMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."ATTACHMENTS_PK" ON "SNECH_DB"."ATTACHMENTS" ("ATTACHMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ISSUE_COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."ISSUE_COMMENTS_PK" ON "SNECH_DB"."ISSUE_COMMENTS" ("ISSUE_COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ISSUE_LOGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."ISSUE_LOGS_PK" ON "SNECH_DB"."ISSUE_LOGS" ("ISSUE_LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ISSUE_LOG_TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."ISSUE_LOG_TYPES_PK" ON "SNECH_DB"."ISSUE_LOG_TYPES" ("LOG_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ISSUE_PRIORITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."ISSUE_PRIORITIES_PK" ON "SNECH_DB"."ISSUE_PRIORITIES" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ISSUES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."ISSUES_PK" ON "SNECH_DB"."ISSUES" ("ISSUE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ISSUES_SUBJECT_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."ISSUES_SUBJECT_UK" ON "SNECH_DB"."ISSUES" ("SUBJECT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ISSUE_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."ISSUE_STATUS_PK" ON "SNECH_DB"."ISSUE_STATUS" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MESSAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."MESSAGES_PK" ON "SNECH_DB"."MESSAGES" ("MESSAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."NOTICES_PK" ON "SNECH_DB"."NOTICES" ("NOTICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_LOGINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."USER_LOGINS_PK" ON "SNECH_DB"."USER_LOGINS" ("LOGIN", "LOGIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_LOGINS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."USER_LOGINS_PK1" ON "SNECH_DB"."USER_LOGINS" ("LOGIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_LOGINS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."USER_LOGINS_UK1" ON "SNECH_DB"."USER_LOGINS" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."USER_ROLES_PK" ON "SNECH_DB"."USER_ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SNECH_DB"."USERS_PK" ON "SNECH_DB"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ATTACHMENTS" MODIFY ("ATTACHMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ATTACHMENTS" MODIFY ("FILE_URL" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ATTACHMENTS" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ATTACHMENTS" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ATTACHMENTS" ADD CONSTRAINT "ATTACHMENTS_PK" PRIMARY KEY ("ATTACHMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUE_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ISSUE_COMMENTS" MODIFY ("ISSUE_COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_COMMENTS" MODIFY ("ISSUE_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_COMMENTS" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_COMMENTS" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_COMMENTS" ADD CONSTRAINT "ISSUE_COMMENTS_PK" PRIMARY KEY ("ISSUE_COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUE_LOGS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ISSUE_LOGS" MODIFY ("ISSUE_LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_LOGS" MODIFY ("ISSUE_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_LOGS" MODIFY ("ISSUE_LOG_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_LOGS" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_LOGS" ADD CONSTRAINT "ISSUE_LOGS_PK" PRIMARY KEY ("ISSUE_LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUE_LOG_TYPES
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ISSUE_LOG_TYPES" MODIFY ("LOG_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_LOG_TYPES" MODIFY ("LOG_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_LOG_TYPES" ADD CONSTRAINT "ISSUE_LOG_TYPES_PK" PRIMARY KEY ("LOG_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUE_LOG_TYPES" ADD CONSTRAINT "ISSUE_LOG_TYPES_NAME_CONST" CHECK (log_type_name IN ('vytvorenie', 'zmazanie', 'zmena_stavu', 'upraveny', 'iny')) ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUE_PRIORITIES
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ISSUE_PRIORITIES" ADD CONSTRAINT "ISSUE_PRIORITIES_CODE_CONST" CHECK (code IN ('A', 'B', 'C', 'D', 'E')) ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUE_PRIORITIES" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_PRIORITIES" ADD CONSTRAINT "ISSUE_PRIORITIES_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUES
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ISSUES" ADD CONSTRAINT "ISSUES_SUBJECT_UK" UNIQUE ("SUBJECT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUES" MODIFY ("LAST_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUES" MODIFY ("USER_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUES" MODIFY ("ISSUE_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUES" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUES" MODIFY ("CODE_PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUES" MODIFY ("CODE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUES" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUES" ADD CONSTRAINT "ISSUES_PK" PRIMARY KEY ("ISSUE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ISSUE_STATUS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ISSUE_STATUS" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."ISSUE_STATUS" ADD CONSTRAINT "ISSUE_STATUSES_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUE_STATUS" ADD CONSTRAINT "ISSUE_STATUS_NAME_CONST" CHECK (code IN ('NOVA', 'PREBIEHA', 'VYRIESENE', 'ZAMIETNUTE', 'INY')) ENABLE;
--------------------------------------------------------
--  Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."MESSAGES" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."MESSAGES" MODIFY ("FROM_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."MESSAGES" MODIFY ("TO_USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."MESSAGES" MODIFY ("READ" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."MESSAGES" MODIFY ("SENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."MESSAGES" ADD CONSTRAINT "MESSAGES_PK" PRIMARY KEY ("MESSAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTICES
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."NOTICES" MODIFY ("NOTICE_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."NOTICES" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."NOTICES" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."NOTICES" MODIFY ("VISIBLE" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."NOTICES" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."NOTICES" ADD CONSTRAINT "NOTICES_PK" PRIMARY KEY ("NOTICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_LOGINS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."USER_LOGINS" ADD CONSTRAINT "USER_LOGINS_UK1" UNIQUE ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SNECH_DB"."USER_LOGINS" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USER_LOGINS" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USER_LOGINS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USER_LOGINS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USER_LOGINS" MODIFY ("USER_ROLES_ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USER_LOGINS" ADD CONSTRAINT "USER_LOGINS_PK" PRIMARY KEY ("LOGIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USER_ROLES" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SNECH_DB"."USER_ROLES" ADD CONSTRAINT "USER_ROLESNAME_CONST" CHECK (role_name IN ('user', 'developer', 'admin')) ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USERS" MODIFY ("CREATED_ON" NOT NULL ENABLE);
  ALTER TABLE "SNECH_DB"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ATTACHMENTS" ADD CONSTRAINT "ATTACHMENTS_ISSUES_FK" FOREIGN KEY ("ISSUE_ID")
	  REFERENCES "SNECH_DB"."ISSUES" ("ISSUE_ID") ENABLE;
  ALTER TABLE "SNECH_DB"."ATTACHMENTS" ADD CONSTRAINT "ATTACHMENTS_MESSAGES_FK" FOREIGN KEY ("MESSAGE_ID")
	  REFERENCES "SNECH_DB"."MESSAGES" ("MESSAGE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ISSUE_COMMENTS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ISSUE_COMMENTS" ADD CONSTRAINT "ISSUE_COMMENTS_ISSUES_FK" FOREIGN KEY ("ISSUE_ID")
	  REFERENCES "SNECH_DB"."ISSUES" ("ISSUE_ID") ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUE_COMMENTS" ADD CONSTRAINT "ISSUE_COMMENTS_USERS_FK" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "SNECH_DB"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ISSUE_LOGS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ISSUE_LOGS" ADD CONSTRAINT "ISSUE_LOGS_ISSUES_FK" FOREIGN KEY ("ISSUE_ID")
	  REFERENCES "SNECH_DB"."ISSUES" ("ISSUE_ID") ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUE_LOGS" ADD CONSTRAINT "ISSUE_LOGS_ISSUE_LOG_TYPES_FK" FOREIGN KEY ("ISSUE_LOG_TYPE_ID")
	  REFERENCES "SNECH_DB"."ISSUE_LOG_TYPES" ("LOG_TYPE_ID") ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUE_LOGS" ADD CONSTRAINT "ISSUE_LOGS_USERS_FK" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "SNECH_DB"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ISSUES
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."ISSUES" ADD CONSTRAINT "ADMIN_ID_FK" FOREIGN KEY ("ADMIN_LOGIN")
	  REFERENCES "SNECH_DB"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUES" ADD CONSTRAINT "PRIORITY_CODE_FK" FOREIGN KEY ("CODE_PRIORITY")
	  REFERENCES "SNECH_DB"."ISSUE_PRIORITIES" ("CODE") ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUES" ADD CONSTRAINT "STATUS_CODE_FK" FOREIGN KEY ("CODE_STATUS")
	  REFERENCES "SNECH_DB"."ISSUE_STATUS" ("CODE") ENABLE;
  ALTER TABLE "SNECH_DB"."ISSUES" ADD CONSTRAINT "USER_LOGIN_FK" FOREIGN KEY ("USER_LOGIN")
	  REFERENCES "SNECH_DB"."USER_LOGINS" ("LOGIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."MESSAGES" ADD CONSTRAINT "FROM_USER_ID" FOREIGN KEY ("FROM_USER_ID")
	  REFERENCES "SNECH_DB"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICES
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."NOTICES" ADD CONSTRAINT "NOTICES_USERS_FK" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "SNECH_DB"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_LOGINS
--------------------------------------------------------

  ALTER TABLE "SNECH_DB"."USER_LOGINS" ADD CONSTRAINT "USER_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "SNECH_DB"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SNECH_DB"."USER_LOGINS" ADD CONSTRAINT "USER_ROLE" FOREIGN KEY ("USER_ROLES_ROLE_ID")
	  REFERENCES "SNECH_DB"."USER_ROLES" ("ROLE_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ISSUES_ISSUE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SNECH_DB"."ISSUES_ISSUE_ID_TRG" BEFORE
  INSERT ON issues FOR EACH ROW   WHEN (NEW.issue_ID IS NULL OR NEW.issue_ID IS NOT NULL) BEGIN :NEW.issue_ID := issue_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SNECH_DB"."ISSUES_ISSUE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MESSAGES_MESSAGE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SNECH_DB"."MESSAGES_MESSAGE_ID_TRG" BEFORE
  INSERT ON messages FOR EACH ROW   WHEN (NEW.message_ID IS NULL) BEGIN :NEW.message_ID := messages_message_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SNECH_DB"."MESSAGES_MESSAGE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_LOGIN_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SNECH_DB"."USER_LOGIN_ID_TRG" BEFORE
  INSERT ON user_logins FOR EACH ROW   WHEN (NEW.login_ID IS NULL) BEGIN :NEW.login_ID := user_login_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SNECH_DB"."USER_LOGIN_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_ROLES_ROLE_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SNECH_DB"."USER_ROLES_ROLE_ID_TRG" BEFORE
  INSERT ON user_roles FOR EACH ROW   WHEN (NEW.role_id IS NULL) BEGIN :NEW.role_id := user_roles_role_id_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SNECH_DB"."USER_ROLES_ROLE_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_USER_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SNECH_DB"."USERS_USER_ID_TRG" BEFORE
  INSERT ON users FOR EACH ROW   WHEN (NEW.user_ID IS NULL) BEGIN :NEW.user_ID := users_user_ID_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "SNECH_DB"."USERS_USER_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Package USER_SECURITY
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "SNECH_DB"."USER_SECURITY" AS

  FUNCTION get_hash (p_username  IN  VARCHAR2,
                     p_password  IN  VARCHAR2)
    RETURN VARCHAR2;
    
  PROCEDURE add_user (p_username  IN  VARCHAR2,
                      p_password  IN  VARCHAR2);

  PROCEDURE change_password (p_username      IN  VARCHAR2,
                             p_old_password  IN  VARCHAR2,
                             p_new_password  IN  VARCHAR2);

  PROCEDURE valid_user (p_username  IN  VARCHAR2,
                        p_password  IN  VARCHAR2);

  FUNCTION valid_user (p_username  IN  VARCHAR2,
                       p_password  IN  VARCHAR2)
    RETURN BOOLEAN;

END;

/
